development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:29c0158b9de27dff88ac29fa3345ca00@barb.redistogo.com:9904/
  channel_prefix: finance-tracker_production
