default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: finance-tracker_development

test:
  <<: *default
  database: finance-tracker_test

legacy: 
  adapter: mysql2
  username: root
  password: password 
  database: legacy_database
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  <<: *default
  database: finance-tracker_production
  username: finance-tracker
  password: <%= ENV['FINANCE-TRACKER_DATABASE_PASSWORD'] %>


